### ISSUE TITLE
Share deployed example

### ISSUE THREAD

**Issue by sedubois** [ReggaePanda/redux-offline-examples#1]
It would be great if you could share a deployment of the Apollo example to see how it behaves. Maybe use https://deploy.now.sh?

**Comment by ManAnRuck** [comment]
good idea, I'll try it.

**Comment by ManAnRuck** [comment]
here now the demo :)
https://apollo-web-lohecdnuxh.now.sh

**Comment by sedubois** [comment]
Great :) might also be nicer to use an alias for prettier URL (`now alias https://apollo-web-lohecdnuxh.now.sh apollo-web`).

**Comment by ManAnRuck** [comment]
https://apollo-web.now.sh done :) thank you
