### ISSUE TITLE
Doesn't work offline

### ISSUE THREAD

**Issue by sedubois** [ReggaePanda/redux-offline-examples#3]
I tried to open the website while offline, after having opened it while online, but the page doesn't load. Tested on iPhone safari. iOS 10.3.1.

**Comment by devrchancay** [comment]
I'm pretty sure that IOS does not support PWA.
But you are already working on that try to try on an Android device

**Comment by ManAnRuck** [comment]
@devrchancay yes, not default, but you can use some technics to do it. Now I try work with react-apollo and apollo-cache-persist

**Comment by sedubois** [comment]
PWA are coming in iOS 11.3 so the situation could be checked when it gets released

**Comment by devrchancay** [comment]
knowing that, I think we can close this issue
